apiVersion: v1
kind: Pod
metadata:
  name: systest
spec:
  restartPolicy: OnFailure
  containers:
  - name: ytentry
    image: {{ .Values.SystestImagePath }}
    env:
    - name: YT_CONFIG_PATCHES
      value: '{proxy={enable_proxy_discovery=%false}}'
    - name: YT_TOKEN
      value: 'password'
    - name: YT_LOG_LEVEL
      value: 'info'
    - name: YT_PROXY
      value: "$(HTTP_PROXIES_LB_SERVICE_HOST):$(HTTP_PROXIES_LB_SERVICE_PORT)"
    command: ['systest', '-n', '4', '--ipv4', 'true', '--enable-reduce', 'true', '--enable-renames', 'true', '--enable-deletes', 'false']
