{{- if and .Values.microservices.bulkAclChecker.enabled .Values.microservices.bulkAclChecker.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ytmsvc.fullname" . }}-bulk-acl-checker-service
  labels:
    {{- include "ytmsvc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: bulk-acl-checker
spec:
  type: {{ .Values.microservices.bulkAclChecker.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.microservices.bulkAclChecker.api.service.port }}
      targetPort: http
  selector:
    {{- include "ytmsvc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bulk-acl-checker
{{- end }}
