{{- if and .Values.microservices.idToPathUpdater.enabled .Values.microservices.idToPathUpdater.preprocessing.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ytmsvc.cronjob.fullname" (dict "root" . "suffix" "id-to-path-preprocessing") }}
  labels:
    {{- include "ytmsvc.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: id-to-path-updater
spec:
  schedule: {{ .Values.microservices.idToPathUpdater.preprocessing.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.microservices.idToPathUpdater.preprocessing.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.microservices.idToPathUpdater.preprocessing.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.microservices.idToPathUpdater.preprocessing.startingDeadlineSeconds }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.microservices.idToPathUpdater.preprocessing.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "ytmsvc.commonLabels" . | nindent 12 }}
            app.kubernetes.io/component: resource-usage-preprocessing
        spec:
          {{- with (.Values.microservices.idToPathUpdater.image.imagePullSecrets | default .Values.imagePullSecrets) }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "ytmsvc.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
          - name: {{ .Chart.Name }}-{{ .Values.cluster.name | replace "_" "-" }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: {{ include "ytmsvc.image" (dict "image" .Values.microservices.idToPathUpdater.image "root" .) }}
            imagePullPolicy: {{ .Values.microservices.idToPathUpdater.image.pullPolicy | default .Values.image.pullPolicy }}
            args:
              - "./id_to_path_updater"
              - "--cluster"
              - {{ .Values.cluster.proxy | quote }}
              - "--tmp-path"
              - {{ .Values.microservices.idToPathUpdater.config.tmpPath | quote }}
              - "--output-table"
              - {{ .Values.microservices.idToPathUpdater.config.outputTable | quote }}
              - "--force-cluster"
              - {{ .Values.cluster.name | quote }}
              - "--input-directory"
              - {{ .Values.microservices.idToPathUpdater.config.inputTablesSource | quote }}
            env:
              - name: YT_PROXY
                value: {{ .Values.cluster.proxy | quote }}
            envFrom:
            {{- with .Values.microservices.idToPathUpdater.secretRefs | default .Values.secretRefs }}
              {{- range . }}
              - secretRef:
                  name: {{ . }}
              {{- end }}
            {{- end }}
            resources:
              {{- toYaml (.Values.microservices.idToPathUpdater.resources | default .Values.resources) | nindent 14 }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
{{- end }}
