{{- range $jobName, $jobData := (merge .Values.jobs .Values.additionalJobs) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" (include ".fullname" $) (include ".cronJobSlug" (dict "name" $jobName)) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include ".labels" $ | nindent 4 }}
spec:
  schedule: {{ $jobData.schedule | default $.Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ $.Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $.Values.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ $.Values.startingDeadlineSeconds }}
  concurrencyPolicy: {{ $jobData.concurrencyPolicy | default $.Values.concurrencyPolicy | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include ".serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          {{- if and $jobData.jobs $jobData.jobDescriptions }}
          initContainers:
          {{- range $seqJobName := $jobData.jobs }}
          {{- $seqJobDetails := (index $jobData.jobDescriptions $seqJobName) }}
          - name: {{ include ".cronJobSlug" (dict "name" $seqJobName) }}
            {{- include ".containerBody" $ | nindent 12 }}
            args:
              {{- range $arg := $seqJobDetails.args }}
              - {{ $arg }}
              {{- end }}
          {{- end }}
          containers:
          - name: sequence-complete-marker
            {{- include ".containerBody" $ | nindent 12 }}
            command: ["echo", "All sequential jobs completed successfully for {{ $jobName }}"]
          {{- else }}
          containers:
          - name: {{ include ".cronJobSlug" (dict "name" $jobName) }}
            {{- include ".containerBody" $ | nindent 12 }}
            args:
              {{- range $arg := $jobData.args }}
              - {{ $arg }}
              {{- end }}
          {{- end }}
          {{- with $.Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $jobData.restartPolicy }}
  suspend: {{ not $jobData.enabled }}
---
{{- end }}
