main:
  source: dev
0.23.1: &operator_0_23_1
  source: stable
0.24.0:
  <<: *operator_0_23_1
0.25.0:
  <<: *operator_0_23_1
0.26.0:
  <<: *operator_0_23_1
0.27.0:
  <<: *operator_0_23_1
0.28.0:
  <<: *operator_0_23_1
0.29.0:
  <<: *operator_0_23_1
0.30.0:
  <<: *operator_0_23_1
