main:
  source: dev
  constraints:
    operator: main
    ytsaurus: main
0.0.8:
  source: stable
  constraints:
    operator: ">=0.25.0"
    ytsaurus: ">=24.2"
0.0.11:
  source: stable
  constraints:
    operator: ">=0.25.0 && main"
    ytsaurus: ">=24.2"
0.1:
  source: release
  constraints:
    operator: ">=0.25.0 && main"
    ytsaurus: ">=25.2"