on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
      publish-strawberry:
        required: false
        default: false
        type: boolean
      publish-ytsaurus:
        required: false
        default: false
        type: boolean
      publish-query-tracker:
        required: false
        default: false
        type: boolean
      publish-chyt:
        required: false
        default: false
        type: boolean
      publish-local:
        required: false
        default: false
        type: boolean
      image-tag:
        required: true
        type: string
      nightly-image-tag:
        required: true
        type: string

    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      GH_USERNAME:
        required: true

jobs:
  docker:
    runs-on: ${{ inputs.runs-on-value }}
    steps:
      - name: Docker login
        shell: bash
        run: |
          echo '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' | docker login ghcr.io --username ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Core image
        if: ${{ inputs.publish-ytsaurus }}
        run: |
          mkdir -p ../docker-ytsaurus-build
          IMAGE_TAG=${{ inputs.image-tag }}
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component ytsaurus --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/ytsaurus:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/ytsaurus:${IMAGE_TAG} ghcr.io/ytsaurus/ytsaurus-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/ytsaurus-nightly:${NIGHTLY_IMAGE_TAG}

      - name: Query tracker image
        if: ${{ inputs.publish-query-tracker }}
        run: |
          mkdir -p ../docker-query-tracker-build
          IMAGE_TAG=${{ inputs.image-tag }}
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component query-tracker --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --yql-build-path ../build_qt --output-path ../docker-query-tracker-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/query-tracker:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/query-tracker:${IMAGE_TAG} ghcr.io/ytsaurus/query-tracker-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/query-tracker-nightly:${NIGHTLY_IMAGE_TAG}

      - name: CHYT image
        if: ${{ inputs.publish-chyt }}
        run: |
          mkdir -p ../docker-chyt-build
          IMAGE_TAG=${{ inputs.image-tag }}
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component chyt --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-chyt-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/chyt:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/chyt:${IMAGE_TAG} ghcr.io/ytsaurus/chyt-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/chyt-nightly:${NIGHTLY_IMAGE_TAG}

      - name: Strawberry image
        if: ${{ inputs.publish-strawberry }}
        run: |
          mkdir -p ../docker-strawberry-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component strawberry --ytsaurus-source-path $(pwd)/ytsaurus --output-path ../docker-strawberry-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/strawberry:${IMAGE_TAG}
          fi

      - name: Local image
        if: ${{ inputs.publish-local }}
        run: |
          mkdir -p ../docker-local-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component local --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-local-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          docker push ghcr.io/ytsaurus/local:${IMAGE_TAG}

      - name: Core image (relwithdebinfo)
        if: ${{ inputs.publish-ytsaurus }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component ytsaurus --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/ytsaurus:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/ytsaurus:${IMAGE_TAG} ghcr.io/ytsaurus/ytsaurus-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/ytsaurus-nightly:${NIGHTLY_IMAGE_TAG}

      - name: Query tracker image (relwithdebinfo)
        if: ${{ inputs.publish-query-tracker }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all || true
          mv ../build_relwithdebinfo/yt/yql/agent/bin/ytserver-yql-agent ../build/yt/yql/agent/bin/ytserver-yql-agent || true

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component query-tracker --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --yql-build-path ../build_qt_relwithdebinfo --output-path ../docker-query-tracker-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/query-tracker:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/query-tracker:${IMAGE_TAG} ghcr.io/ytsaurus/query-tracker-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/query-tracker-nightly:${NIGHTLY_IMAGE_TAG}

      - name: Chyt image (relwithdebinfo)
        if: ${{ inputs.publish-chyt }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/chyt/server/bin/ytserver-clickhouse ../build/yt/chyt/server/bin/ytserver-clickhouse

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component chyt --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-chyt-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          if ! [[ ${IMAGE_TAG} =~ "dev" || ${IMAGE_TAG} =~ "hotfix" ]]; then
            docker push ghcr.io/ytsaurus/chyt:${IMAGE_TAG}
          fi
          docker tag ghcr.io/ytsaurus/chyt:${IMAGE_TAG} ghcr.io/ytsaurus/chyt-nightly:${NIGHTLY_IMAGE_TAG}
          docker push ghcr.io/ytsaurus/chyt-nightly:${NIGHTLY_IMAGE_TAG}


      - name: Local image (relwithdebinfo)
        if: ${{ inputs.publish-local }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all || true

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --component local --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-local-build --image-tag ${IMAGE_TAG} --image-cr ghcr.io/

          docker push ghcr.io/ytsaurus/local:${IMAGE_TAG}

