name: Docker jobs
on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
      cpp-build-system:
        required: false
        # cmake or ya-make
        type: string
        default: cmake
      publish-strawberry:
        required: false
        default: false
        type: boolean
      publish-ytsaurus:
        required: false
        default: false
        type: boolean
      publish-query-tracker:
        required: false
        default: false
        type: boolean
      publish-chyt:
        required: false
        default: false
        type: boolean
      publish-local:
        required: false
        default: false
        type: boolean
      image-tag:
        required: true
        type: string
      nightly-image-tag:
        required: true
        type: string

    secrets:
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
      GH_USERNAME:
        required: true

jobs:
  docker:
    runs-on: ${{ inputs.runs-on-value }}
    strategy:
      matrix:
        build-type: [release]

    steps:
      - name: Calculate variables
        id: vars
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}
          NIGHTLY_IMAGE_TAG=${{ inputs.nightly-image-tag }}
          if [[ ${{ matrix.build-type }} =~ "relwithdebinfo" ]]; then
            IMAGE_TAG=${IMAGE_TAG}-relwithdebinfo
            NIGHTLY_IMAGE_TAG=${NIGHTLY_IMAGE_TAG}-relwithdebinfo
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "NIGHTLY_IMAGE_TAG=$NIGHTLY_IMAGE_TAG" >> $GITHUB_OUTPUT

          YTSAURUS_BUILD_PATH="../build_${{ inputs.cpp-build-system}}_${{ matrix.build-type}}"
          YQL_BUILD_PATH="../build_yql_${{ inputs.cpp-build-system}}_${{ matrix.build-type}}"
          echo "YTSAURUS_BUILD_PATH=$YTSAURUS_BUILD_PATH" >> $GITHUB_OUTPUT
          echo "YQL_BUILD_PATH=$YQL_BUILD_PATH" >> $GITHUB_OUTPUT

      - name: Docker login
        run: |
          echo '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' | docker login ghcr.io --username ${{ secrets.GH_USERNAME }} --password-stdin

      - name: YTsaurus image (${{ inputs.cpp-build-system }}, ${{ matrix.build-type }})
        if: ${{ inputs.publish-ytsaurus }}
        run: |
          output_path=../docker-${{ inputs.component}}-${{ inputs.cpp-build-system }}-${{ matrix.build-type }}
          mkdir -p $output_path

          ./ytsaurus/yt/docker/ytsaurus/build.sh --component ytsaurus --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ${{ steps.vars.outputs.YTSAURUS_BUILD_PATH }} --output-path $output_path --image-tag ${{ steps.vars.outputs.IMAGE_TAG }} --image-cr ghcr.io/

          if ! [[ ${{ steps.vars.outputs.IMAGE_TAG }} =~ "dev" ]]; then
            docker push ghcr.io/ytsaurus/ytsaurus:${{ steps.vars.outputs.IMAGE_TAG }}
          fi
          docker tag ghcr.io/ytsaurus/ytsaurus:${{ steps.vars.outputs.IMAGE_TAG }} ghcr.io/ytsaurus/ytsaurus-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
          docker push ghcr.io/ytsaurus/ytsaurus-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}

      - name: Query tracker image (${{ inputs.cpp-build-system }}, ${{ matrix.build-type }})
        if: ${{ inputs.publish-query-tracker }}
        run: |
          output_path=../docker-query-tracker-${{ inputs.cpp-build-system }}-${{ matrix.build-type }}
          mkdir -p $output_path

          ./ytsaurus/yt/docker/ytsaurus/build.sh --component query-tracker --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ${{ steps.vars.outputs.YTSAURUS_BUILD_PATH }} --yql-build-path ${{ steps.vars.outputs.YQL_BUILD_PATH }} --output-path $output_path --image-tag ${{ steps.vars.outputs.IMAGE_TAG }} --image-cr ghcr.io/

          if ! [[ ${{ steps.vars.outputs.IMAGE_TAG }} =~ "dev" ]]; then
            docker push ghcr.io/ytsaurus/query-tracker:${{ steps.vars.outputs.IMAGE_TAG }}
          fi
          docker tag ghcr.io/ytsaurus/query-tracker:${{ steps.vars.outputs.IMAGE_TAG }} ghcr.io/ytsaurus/query-tracker-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
          docker push ghcr.io/ytsaurus/query-tracker-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}

      - name: CHYT image (${{ inputs.cpp-build-system }}, ${{ matrix.build-type }})
        if: ${{ inputs.publish-chyt }}
        run: |
          output_path=../docker-chyt-${{ inputs.cpp-build-system }}-${{ matrix.build-type }}
          mkdir -p $output_path

          ./ytsaurus/yt/docker/ytsaurus/build.sh --component chyt --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ${{ steps.vars.outputs.YTSAURUS_BUILD_PATH }} --output-path $output_path --image-tag ${{ steps.vars.outputs.IMAGE_TAG }} --image-cr ghcr.io/

          if ! [[ ${{ steps.vars.outputs.IMAGE_TAG }} =~ "dev" ]]; then
            docker push ghcr.io/ytsaurus/chyt:${{ steps.vars.outputs.IMAGE_TAG }}
          fi
          docker tag ghcr.io/ytsaurus/chyt:${{ steps.vars.outputs.IMAGE_TAG }} ghcr.io/ytsaurus/chyt-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
          docker push ghcr.io/ytsaurus/chyt-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}

      - name: Strawberry image
        if: ${{ inputs.publish-strawberry }}
        run: |
          output_path=../docker-strawberry-${{ inputs.cpp-build-system }}-${{ matrix.build-type }}
          mkdir -p $output_path

          ./ytsaurus/yt/docker/ytsaurus/build.sh --component strawberry --ytsaurus-source-path $(pwd)/ytsaurus --output-path $output_path --image-tag ${{ steps.vars.outputs.IMAGE_TAG }} --image-cr ghcr.io/

          if ! [[ ${{ steps.vars.outputs.IMAGE_TAG }} =~ "dev" ]]; then
            docker push ghcr.io/ytsaurus/strawberry:${{ steps.vars.outputs.IMAGE_TAG }}
          fi
          docker tag ghcr.io/ytsaurus/strawberry:${{ steps.vars.outputs.IMAGE_TAG }} ghcr.io/ytsaurus/strawberry-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
          docker push ghcr.io/ytsaurus/strawberry-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}

      - name: Local image (${{ inputs.cpp-build-system }}, ${{ matrix.build-type }})
        if: ${{ inputs.publish-local }}
        run: |
          output_path=../docker-local-${{ inputs.cpp-build-system }}-${{ matrix.build-type }}
          mkdir -p $output_path

          ./ytsaurus/yt/docker/ytsaurus/build.sh --component local --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ${{ steps.vars.outputs.YTSAURUS_BUILD_PATH }} --yql-build-path ${{ steps.vars.outputs.YQL_BUILD_PATH }} --output-path $output_path --image-tag ${{ steps.vars.outputs.IMAGE_TAG }} --image-cr ghcr.io/

          docker push ghcr.io/ytsaurus/local:${{ steps.vars.outputs.IMAGE_TAG }}
          docker tag ghcr.io/ytsaurus/local:${{ steps.vars.outputs.IMAGE_TAG }} ghcr.io/ytsaurus/local-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
          docker push ghcr.io/ytsaurus/local-nightly:${{ steps.vars.outputs.NIGHTLY_IMAGE_TAG }}
