on:
  workflow_call:
    inputs:
      runs-on-value:
        required: true
        type: string
      publish-strawberry:
        required: false
        default: false
        type: boolean
      publish-ytsaurus:
        required: false
        default: false
        type: boolean
      publish-query-tracker:
        required: false
        default: false
        type: boolean
      publish-chyt:
        required: false
        default: false
        type: boolean
      publish-local:
        required: false
        default: false
        type: boolean
      image-tag:
        required: true
        type: string
    secrets:
      DOCKER_HUB_LOGIN:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ${{ inputs.runs-on-value }}
    steps:
      - name: DockerHub login
        shell: bash
        run: |
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

      - name: Core image
        if: ${{ inputs.publish-ytsaurus }}
        run: |
          mkdir -p ../docker-ytsaurus-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/ytsaurus:${IMAGE_TAG}
          docker tag ytsaurus/ytsaurus:${IMAGE_TAG} ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}
          docker push ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}

      - name: Query tracker image
        if: ${{ inputs.publish-query-tracker }}
        run: |
          mkdir -p ../docker-query-tracker-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/query-tracker/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --qt-build-path ../build_qt --output-path ../docker-query-tracker-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/query-tracker:${IMAGE_TAG}
          docker tag ytsaurus/query-tracker:${IMAGE_TAG} ytsaurus/query-tracker-nightly:${IMAGE_TAG}-${GITHUB_SHA}
          docker push ytsaurus/query-tracker-nightly:${IMAGE_TAG}-${GITHUB_SHA}

      - name: CHYT image
        if: ${{ inputs.publish-chyt }}
        run: |
          mkdir -p ../docker-chyt-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/chyt/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --chyt-build-path ../build/yt/chyt --output-path ../docker-chyt-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/chyt:${IMAGE_TAG}

      - name: Strawberry image
        if: ${{ inputs.publish-strawberry }}
        run: |
          mkdir -p ../docker-strawberry-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/strawberry/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-strawberry-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/strawberry:${IMAGE_TAG}

      - name: Local image
        if: ${{ inputs.publish-local }}
        run: |
          mkdir -p ../docker-local-build
          IMAGE_TAG=${{ inputs.image-tag }}

          bash ./ytsaurus/yt/docker/local/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-local-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/local:${IMAGE_TAG}

      - name: Core image (relwithdebinfo)
        if: ${{ inputs.publish-ytsaurus }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all

          bash ./ytsaurus/yt/docker/ytsaurus/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-ytsaurus-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/ytsaurus:${IMAGE_TAG}
          docker tag ytsaurus/ytsaurus:${IMAGE_TAG} ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}
          docker push ytsaurus/ytsaurus-nightly:${IMAGE_TAG}-${GITHUB_SHA}

      - name: Query tracker image (relwithdebinfo)
        if: ${{ inputs.publish-query-tracker }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all || true
          mv ../build_relwithdebinfo/yt/yql/agent/bin/ytserver-yql-agent ../build/yt/yql/agent/bin/ytserver-yql-agent || true

          bash ./ytsaurus/yt/docker/query-tracker/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --qt-build-path ../build_qt_relwithdebinfo --output-path ../docker-query-tracker-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/query-tracker:${IMAGE_TAG}
          docker tag ytsaurus/query-tracker:${IMAGE_TAG} ytsaurus/query-tracker-nightly:${IMAGE_TAG}-${GITHUB_SHA}
          docker push ytsaurus/query-tracker-nightly:${IMAGE_TAG}-${GITHUB_SHA}

      - name: Chyt image (relwithdebinfo)
        if: ${{ inputs.publish-chyt }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/chyt/server/bin/ytserver-clickhouse ../build/yt/chyt/server/bin/ytserver-clickhouse

          bash ./ytsaurus/yt/docker/chyt/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --chyt-build-path ../build/yt/chyt --output-path ../docker-chyt-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/chyt:${IMAGE_TAG}

      - name: Local image (relwithdebinfo)
        if: ${{ inputs.publish-local }}
        run: |
          IMAGE_TAG=${{ inputs.image-tag }}-relwithdebinfo

          mv ../build_relwithdebinfo/yt/yt/server/all/ytserver-all ../build/yt/yt/server/all/ytserver-all || true

          bash ./ytsaurus/yt/docker/local/build.sh --ytsaurus-source-path $(pwd)/ytsaurus --ytsaurus-build-path ../build --output-path ../docker-local-build --image-tag ${IMAGE_TAG}

          docker push ytsaurus/local:${IMAGE_TAG}

