name: Issue notifications

on:
  issues:
    types: [opened]

jobs:
  telegram:
    name: Telegram
    runs-on: trampoline
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            New issue in *${{github.repository}}*: `${{github.event.issue.title}}`
            ${{github.server_url}}/${{github.repository}}/issues/${{github.event.issue.number}}

