name: Release tutorial generator

on:
  push:
    tags:
      - 'docker/tutorial/0\.[0-9]+\.[0-9]+*'

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: |
          echo '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' | docker login ghcr.io --username ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Parse Tag
        id: tag
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/docker/tutorial/})" >> $GITHUB_OUTPUT

      - name: Package And Push Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ steps.tag.outputs.RELEASE_VERSION }}"/' yt/docker/charts/tutorial-chart/values.yaml
          helm package yt/docker/charts/tutorial-chart --version ${{ steps.tag.outputs.RELEASE_VERSION }}
          helm push tutorial-chart-${{ steps.tag.outputs.RELEASE_VERSION }}.tgz oci://ghcr.io/ytsaurus

      - name: Build And Push Docker Image
        run: |
          ./ya make -r yt/yt/scripts/tutorial/generate_tutorial --no-src-links -o $(pwd)
          ln -s yt/yt/scripts/tutorial/generate_tutorial/data data
          ln -s yt/yt/scripts/tutorial/generate_tutorial/scripts scripts
          ln yt/yt/scripts/tutorial/generate_tutorial/generate_tutorial generate_tutorial
          docker build -t ghcr.io/ytsaurus/tutorial:${{ steps.tag.outputs.RELEASE_VERSION }} -f ./yt/yt/scripts/tutorial/generate_tutorial/Dockerfile .
          docker push ghcr.io/ytsaurus/tutorial:${{ steps.tag.outputs.RELEASE_VERSION }}
