name: Release YT microservices

on:
  push:
    tags:
      - 'docker/ytmsvc/0\.[0-9]+\.[0-9]+*'

jobs:
  release:
    name: Run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        run: |
          echo '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' | docker login ghcr.io --username ${{ secrets.GH_USERNAME }} --password-stdin
      - name: Parse Tag
        id: tag
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/docker/ytmsvc/})" >> $GITHUB_OUTPUT
      - name: Package And Push Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ steps.tag.outputs.RELEASE_VERSION }}"/' yt/docker/charts/ytmsvc-chart/values.yaml
          helm package yt/docker/charts/ytmsvc-chart --version ${{ steps.tag.outputs.RELEASE_VERSION }}
          helm push ytmsvc-chart-${{ steps.tag.outputs.RELEASE_VERSION }}.tgz oci://ghcr.io/ytsaurus
      - name: Build And Push Docker Image
        run: |
          cd yt/docker/ytmsvc
          make docker-build IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}
          make docker-push IMAGE_TAG=${{ steps.tag.outputs.RELEASE_VERSION }}

